image: python:3.8

stages:
  - cache
  - before_script
  - bridge_api
  - bridge
  - build
  - test
  - deploy
  - complete

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


connect_api:
  stage: bridge_api
  trigger:
    project: breath_unicamp/breath_api_interface
    branch: main
    strategy: depend

connect_data:
  stage: bridge
  trigger:
    project: breath_unicamp/breath_data
    branch: main
    strategy: depend

build_main:
  stage: build
  script:
    - git clone https://gitlab.com/breath_unicamp/breath_data.git
    - git clone https://gitlab.com/breath_unicamp/breath_api_interface.git
    - python3 -m pip install --upgrade build
    - python3 -m build
    - python3 -m pip install .
   
  artifacts:
    paths:
      - public
  
test:
  stage: test
  script:
    - pip3 install pytest
    - pytest test --junitxml=report.xml


pypi_release_breath_data:
    stage: deploy
    script:
        - cd ../breath_data
        - cd module
        - python3 -m pip install --upgrade twine
        - python3 -m t BReATH / wine upload dist/* -u __token__ -p pypi-AgEIcHlwaS5vcmcCJGVmNGRhMGUxLTNmYjgtNGQ1OC04YjIwLTY1YzQzOTUxNzFmNwACPHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJicmVhdGgtZGF0YSJdfSwgInZlcnNpb24iOiAxfQAABiCmPAFXhD3EumQcfVe4juY0tmRcmF_VOwgqvrNlrXDe8g

pypi_release_api:
    stage: deploy
    script:
        - cd module
        - cd ../breath_api_interface
        - python3 -m pip install --upgrade twine
        - python3 -m twine upload dist/* -u __token__ -p pypi-AgEIcHlwaS5vcmcCJDM5NzFmNmU2LTQwNDQtNGU1Zi1iZmEwLTM0MDUyOGU1NWUxOQACRXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJicmVhdGgtYXBpLWludGVyZmFjZSJdfSwgInZlcnNpb24iOiAxfQAABiAq_QNOWfPp58IA141c-1FPIpmuigPhpzaZ4ng062JxAQ

pypi_release:
    stage: deploy
    script:
        - python3 -m pip install --upgrade twine
        - python3 -m twine upload dist/* -u __token__ -p pypi-AgEIcHlwaS5vcmcCJDYwZTFhMGU3LTU1NmItNGY1NS1hMjVmLTU3NzhiMWNkOWIyMAACPHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJicmVhdGgtbWFpbiJdfSwgInZlcnNpb24iOiAxfQAABiD8Q3zG2nhdnsE9_7xY0-fRze5NKfANQkMaWztxzvBDJA
